### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by mihaibujanca** [mp3guy/Kintinuous#1]
Hey, I saw the paper and the youtube video, I find them really cool!
I'm quite eager to try it and maybe help a bit with documenting any other needs of the project, so I was wondering when would the code be available?

Thanks

**Comment by mp3guy** [comment]
e're just sorting out finalising the license, it should be up online in a couple of weeks.

**Comment by mihaibujanca** [comment]
Looking forward to it! There's a lot of stuff I'd like to try :)
