### ISSUE TITLE
 void Deformation::addCameraLoop(): Assertion `deformationGraph' failed.

### ISSUE THREAD

**Issue by fuxingyin** [mp3guy/Kintinuous#11]
Amazing work! 
The code is compiled successfully. But the program unexpectedly finished with the error 'Kintinuous: /.../src/backend/Deformation.cpp:264: void Deformation::addCameraLoop(): Assertion `deformationGraph' failed. The program has unexpectedly finished.'
I wonder if the deformationGraph is not initialized before using. Looking forward to your reply.

**Comment by mp3guy** [comment]
Now that's an interesting error. For some reason the object isn't getting instantiated at https://github.com/mp3guy/Kintinuous/blob/master/src/backend/Deformation.cpp#L500

Not sure where to start debugging this. What data are you processing?

**Comment by fuxingyin** [comment]
I read the code and find out the reason. I use xtion to scan my room. By decreasing the value of  '-dg' the program works my way sometimes. It seems like the place I scanned is not big enough and the pose graph is not initialised due to the value of variable poseCount is less than 4. 

I have read your code ElasticFusion, another great work!
Thanks for your quick reply!

**Comment by mp3guy** [comment]
Yes, that makes sense. Kintinuous isn't meant for small loop closures, ElasticFusion will work much better there.

**Comment by fuxingyin** [comment]
When the scene is very large, ElasticFusion is not suitable. Do you have any desire to optimize the algorithm and code? I think with some improvement Elasticfusion may work better for large scale. I have been followed your work since I work in this area.

**Comment by fuxingyin** [comment]
Thanks for your time. You can close the question now. Keep following your work.
