### ISSUE TITLE
Problem to run demo dataset

### ISSUE THREAD

**Issue by HTLife** [mp3guy/Kintinuous#15]
I had successfully run the sample dataset on my old computer.
However, when I tried to run it on my new PC, it always prompt me this error message:
```
~/code/Kintinuous/build$ ./Kintinuous -s 7 -v ../vocab.yml.gz  -l ../loop.klg -ri -fl -od
Point resolution: 13.6 millimetres
Error: invalid device function	/home/(myusername)/code/Kintinuous/src/frontend/cuda/tsdf_volume.cu:477
```
My hardware spec:
- Mother board: ASUS Z170ar 
- CPU: Intel I7 6700K
- RAM: 16GB
- GPU: NVidia GTX 1060

Environment
- OS Ubuntu 14.04
- CUDA 8.0 (had tried 7.5 but cannot login after installation, so I changed to 8.0)

Installation all followed the "build.sh" file except "cuda".

Did you have any idea on this issue?

---
I tried a lot of combinations of Ubuntu version(14.04, 16.04) and Kitinuous install step, but all combination failed on my new PC.

**Comment by mp3guy** [comment]
Add 61 to CUDA_NVCC_ARCHS in the Core builds CMake configuration

**Comment by HTLife** [comment]
@mp3guy Thanks for your hint.  It works like a charm!

Note for someone who also suffer from this problem:
Kintinuous/src/CMakeLists.txt
Add 61 to Line39
Line39:
`set(CUDA_ARCH_BIN "20 30 35 50 52 61" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is su    pported. Example: 1.3 2.1(1.3) or 13 21(13)")`
