### ISSUE TITLE
DBowInterfaceSurf.cpp:77:16: error: ‘SURF’ in namespace‘ cv’ does not name a type

### ISSUE THREAD

**Issue by maxcr** [mp3guy/Kintinuous#16]
Followed all instructions as they are in build.sh

Using Arch Linux.

**Comment by mp3guy** [comment]
You didn't build OpenCV with the nonfree module, or you already have another version of OpenCV installed that CMake is finding to build Kintinuous

**Comment by maxcr** [comment]
Nevermind I didn't run ldconfig after downgrading the libraries. mp3guy u r god

**Comment by maxcr** [comment]
Now I'm getting a new error.

/sbin/ld: warning: libavformat.so.57, needed by /usr/lib/libvtkIOFFMPEG.so.1, not found (try u

**Comment by mp3guy** [comment]
Looks like you're going to have to go down a big library dependency chain to sort that out. I would not recommend Arch Linux for this reason.

**Comment by maxcr** [comment]
Its actually pretty straight forward. The thing that threw me off is the commit hashes in the README on github must either be incorrect or use some weird unicode formatting. Those hashes never work, but the ones from the build.sh do.

**Comment by maxcr** [comment]
Got it working. If anybody has this problem in the future just type `cmake -rpath /usr/lib ..`
