### ISSUE TITLE
Does not work with cuda 8.0?

### ISSUE THREAD

**Issue by huiyingShen** [mp3guy/Kintinuous#18]
....
Waiting for first frame.. got it!
Error: invalid device function	~/Kintinuous/src/frontend/cuda/tsdf_volume.cu:477

Ubuntu 16.04, cuda 8.0, GeForce GTX 1060, i7-6700HQ

**Comment by mp3guy** [comment]
Add 61 to CUDA_ARCH_BIN in CMakeLists.txt
