### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by pb10** [mp3guy/Kintinuous#25]
Hi, I am an undergraduate student trying to run Kintinuous on my system. I am working with Ubuntu 14.04 and have installed the required dependencies. But on running the command, I get this output:

./Kintinuous -s 7 -v ../vocab.yml.gz -l loop.klg -ri -fl -od
Point resolution: 13.6 millimetres
Error: out of memory	/home/capstone/Kintinuous/src/frontend/cuda/containers/device_memory.cpp:223

Could you please help me out with this? Thanks!

**Comment by HTLife** [comment]
Your GPU memory is not enough for running Kontinuous.  Run it on pc with more GPU memory.

**Comment by HTLife** [comment]
If you still wanna evaluate Kontinuous, but could sacrificing real-time processing.
You could reference this for point 12
https://github.com/HTLife/Kintinuous-installation-guide/blob/master/README.md
to modify memory requirement.

**Comment by pb10** [comment]
It worked! I am very thankful to you sir, had been stuck on it for quite sometime! :)

**Comment by HTLife** [comment]
@pb10 No problem!
Don't forget to close this issue.
