### ISSUE TITLE
how to save a mesh on remote serverwithout GUI

### ISSUE THREAD

**Issue by voyage19941119** [mp3guy/Kintinuous#26]
Thanks a lot for providing kintinuous！
I am runing it on lab server shared with other lab members，remotely through my own computer.so there is no GUI I can use，so I annotate all codes about displaying，then it works well.
now I want to save a mesh，what should I do？

**Comment by HTLife** [comment]
You may found it useful to search "save" related keyword in this project.
https://github.com/mp3guy/Kintinuous/blob/06b19ccb4a043535877acb64df86f69d8895e897/src/backend/IncrementalMesh.cpp

void IncrementalMesh::saveMesh(std::string file)

**Comment by voyage19941119** [comment]
@HTLife 
thanks for help . but I still cannot save the mesh after adding function IncrementalMesh::saveMesh()   in MainController.cpp , specificly in **MainController::mainLoop()**(as picture bellow shows,below **_//change 0_**)
![screenshot from 2017-04-05 16-31-38](https://cloud.githubusercontent.com/assets/11376132/24696891/c681124e-1a1d-11e7-9ed1-7d6c889a43b6.png)
thanks anyway !

**Comment by HTLife** [comment]
You are using that function wrongly.
Provide parameter 
-m : Enable mesh generation.

https://github.com/mp3guy/Kintinuous/blob/fdf77b893abebf85d63cb98eeec4fdd38965a059/src/MainController.cpp#L238

**Comment by voyage19941119** [comment]
yeah ,I found it later ,so I have changed the code(have added -m to enable mesh generation)
![screenshot from 2017-04-07 10-43-18](https://cloud.githubusercontent.com/assets/11376132/24783474/2a96c1cc-1b7f-11e7-9e3e-3019a1a0a20f.png)
and successfully saved a .pcd and .ply
.pcd works fine ,but I cannot open .ply through meshlab
