### ISSUE TITLE
Issue during compilation

### ISSUE THREAD

**Issue by stephane-lb** [mp3guy/Kintinuous#3]
Hi Thomas,

Sorry to disturb you with this, and I just spent hours to try to compile Continuous, unfortunately, I just got an error that I don't know how to fix / bypass : 

```
Linking CXX executable Kintinuous
/usr/bin/ld: libbackend.a(DBowInterfaceSurf.cpp.o): undefined reference to symbol '_ZN2cv4SURFC1Ediibb'
/usr/local/lib/libopencv_nonfree.so.2.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Kintinuous] Error 1
make[1]: *** [CMakeFiles/Kintinuous.dir/all] Error 2
make: *** [all] Error 2
```

I am using an Ubuntu 14.04, and I launched the script given. If you have any idea it would be great !

Thanks for your help,

Stephane

**Comment by mp3guy** [comment]
Did you run the script on a fresh install? If not that's likely the cause of your trouble. Looks like you have a version of OpenCV installed that doesn't have the non-free modules built.

**Comment by stephane-lb** [comment]
I will suppose that I did something wrong, it is a fresh install of ubuntu 14.04. I will uninstall and reinstall openCV hope it would work. Thanks for your help! Stéphane

**Comment by mp3guy** [comment]
Doing the manual OpenCV install is probably causing your problem. The script automatically downloads the correct version and builds it with the necessary modules.
