### ISSUE TITLE
Error: ‘ManagedImage’ in namespace ‘pangolin’ does not name a type pangolin::ManagedImage<uchar3> rgbImg

### ISSUE THREAD

**Issue by sotoglzz** [mp3guy/Kintinuous#37]
##Hello Thomas, thank you for share Kintinuous.

I have the following issue when building Kintinuous:

In file included from /home/trinidad/Kintinuous/src/MainController.h:57:0,
from /home/trinidad/Kintinuous/src/MainController.cpp:19:
/home/trinidad/Kintinuous/src/PangoVis.h:105:9: error: ‘ManagedImage’ in namespace ‘pangolin’ does not name a type pangolin::ManagedImage<uchar3> rgbImg;

Currently, Pangolin has 3 releases. I have installed the 3 versions and all remain the same problem.
I'm in Ubuntu 14.04.

Thanks, in advance

**Comment by mp3guy** [comment]
Don't use a release. Use top of pangolin master

**Comment by sotoglzz** [comment]
Thanks for your reply, that solved the problem
