### ISSUE TITLE
Can kintinuous work with a stereo camera？

### ISSUE THREAD

**Issue by dongmiller** [mp3guy/Kintinuous#50]
I wanna use ZED camera to run kintinuous, can it work? Have someone tried it ?

**Comment by tftangming** [comment]
@dongmiller Hello, Can you run kintinuous using your ZED camera?

**Comment by dongmiller** [comment]
Hi, It works with Zed camera at last. But the &nbsp;reconstruction result with the depth from zed isn’t very well.



发自我的iPhone


------------------ Original ------------------

**Comment by tftangming** [comment]
@dongmiller can you give me some reconstruction result if possible?

**Comment by tftangming** [comment]
@dongmiller you achieve the zed camera reconstruction by the living loading or the dataset loading?
