### ISSUE TITLE
Question about the bag of words database

### ISSUE THREAD

**Issue by dawnos** [mp3guy/Kintinuous#6]
I am working on bag of words, and I found that there is a BoW in your repo. How do you train your BoW? Can you tell me? Thank you!

**Comment by mp3guy** [comment]
You can train one with DBoW2: https://github.com/dorian3d/DBoW2

**Comment by dawnos** [comment]
Thanks for reply! What's your training data?

**Comment by mp3guy** [comment]
A short indoor sequence.

**Comment by dawnos** [comment]
Thank you!
